spring: 
 datasource: 
  url: jdbc:mysql://localhost:3306/test
  username: root
  password: root
  driver-class-name: com.mysql.jdbc.Driver
  test1: 
   url: jdbc:mysql://localhost:3306/test
   username: root
   password: root
   driver-class-name: com.mysql.jdbc.Driver
   testQuery: select 1
  test2: 
   url: jdbc:mysql://localhost:3306/test1
   username: root
   password: root
   driver-class-name: com.mysql.jdbc.Driver
   testQuery: select 1
mybatis:
  mapper-locations: classpath:mapping/*.xml 